name: Build and Push Production

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Deploy to production branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: production # Final files will go to this branch
          FOLDER: dist # Folder to publish
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "🚀 Production Deploy: ({sha}) {msg}"
